In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

print("All File Imported Successfully")
print(tensorflow.__version__)
print(keras.__version__)

All File Imported Successfully
2.19.0
3.13.2

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

In [42]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/mullarohan/dataset_for_machine_learning/refs/heads/main/Admission_Predict.csv"
)
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [43]:
df.drop(columns=["Serial No."], inplace=True)
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65

In [44]:
df.columns = [
    "GRE Score",
    "TOEFL Score",
    "University Rating",
    "SOP",
    "LOR ",
    "CGPA",
    "Research",
    "Chance of Admit",
]
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit'],
      dtype='object')

In [45]:
X = df.drop(columns=["Chance of Admit"], axis=1)
y = df["Chance of Admit"]
# X = df.iloc[:,0:-1]
# y = df.iloc[:,-1]
X, y

(     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
 0          337          118                  4  4.5   4.5  9.65         1
 1          324          107                  4  4.0   4.5  8.87         1
 2          316          104                  3  3.0   3.5  8.00         1
 3          322          110                  3  3.5   2.5  8.67         1
 4          314          103                  2  2.0   3.0  8.21         0
 ..         ...          ...                ...  ...   ...   ...       ...
 495        332          108                  5  4.5   4.0  9.02         1
 496        337          117                  5  5.0   5.0  9.87         1
 497        330          120                  5  4.5   5.0  9.56         1
 498        312          103                  4  4.0   5.0  8.43         0
 499        327          113                  4  4.5   4.5  9.04         0

 [500 rows x 7 columns],
 0      0.92
 1      0.76
 2      0.72
 3      0.80
 4      0.65
        ...
 495    0.87
 496    0.96
 497    0.93
 498    0.73
 499    0.84
 Name: Chance of Admit, Length: 500, dtype: float64)

In [46]:
X_test, X_train, y_test, y_train = train_test_split(
    X, y, test_size=0.2, random_state=42
)
X_test

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
249        321          111                  3  3.5   4.0  8.83         1
433        316          111                  4  4.0   5.0  8.54         0
19         303          102                  3  3.5   3.0  8.50         0
322        314          107                  2  2.5   4.0  8.27         0
332        308          106                  3  3.5   2.5  8.21         1
..         ...          ...                ...  ...   ...   ...       ...
106        329          111                  4  4.5   4.5  9.18         1
270        306          105                  2  2.5   3.0  8.22         1
348        302           99                  1  2.0   2.0  7.25         0
435        309          105                  2  2.5   4.0  7.68         0
102        314          106                  2  4.0   3.5  8.25         0

[400 rows x 7 columns]

In [47]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)
X_train_scaled

array([[0.88      , 0.85185185, 0.75      , 0.75      , 0.625     ,
        0.89430894, 1.        ],
       [0.48      , 0.55555556, 0.75      , 0.875     , 0.75      ,
        0.69105691, 1.        ],
       [0.5       , 0.44444444, 0.25      , 0.25      , 0.375     ,
        0.12601626, 0.        ],
       [0.44      , 0.59259259, 0.5       , 0.5       , 0.5       ,
        0.54878049, 0.        ],
       [0.72      , 0.7037037 , 0.5       , 0.625     , 0.5       ,
        0.69512195, 1.        ],
       [0.78      , 0.66666667, 0.75      , 0.875     , 0.75      ,
        0.76829268, 1.        ],
       [0.        , 0.25925926, 0.        , 0.125     , 0.25      ,
        0.08943089, 0.        ],
       [0.22      , 0.48148148, 0.75      , 0.375     , 0.5       ,
        0.45934959, 0.        ],
       [0.56      , 0.59259259, 0.5       , 0.625     , 0.75      ,
        0.76422764, 1.        ],
       [0.6       , 0.7037037 , 0.75      , 0.5       , 0.875     ,
        0.61788618, 1.        ],
       [0.66      , 0.55555556, 0.5       , 0.625     , 0.5       ,
        0.51219512, 0.        ],
       [0.52      , 0.59259259, 0.5       , 0.625     , 0.5       ,
        0.57723577, 0.        ],
       [0.64      , 0.37037037, 0.75      , 0.5       , 0.375     ,
        0.27642276, 1.        ],
       [1.        , 0.81481481, 1.        , 0.875     , 0.875     ,
        0.85772358, 1.        ],
       [0.68      , 0.62962963, 0.5       , 0.625     , 0.5       ,
        0.76422764, 1.        ],
       [0.12      , 0.14814815, 0.25      , 0.125     , 0.25      ,
        0.18699187, 0.        ],
       [0.84      , 0.55555556, 1.        , 0.875     , 0.75      ,
        0.68292683, 1.        ],
       [0.2       , 0.14814815, 0.25      , 0.5       , 0.5       ,
        0.30894309, 1.        ],
       [0.16      , 0.2962963 , 0.25      , 0.125     , 0.25      ,
        0.21138211, 0.        ],
       [0.14      , 0.2962963 , 0.5       , 0.25      , 0.75      ,
        0.13414634, 1.        ],
       [0.34      , 0.44444444, 0.25      , 0.375     , 0.875     ,
        0.31707317, 1.        ],
       [0.14      , 0.22222222, 0.75      , 0.5       , 0.625     ,
        0.19105691, 0.        ],
       [0.42      , 0.33333333, 0.5       , 0.875     , 0.75      ,
        0.52845528, 1.        ],
       [0.74      , 0.59259259, 0.5       , 0.625     , 0.75      ,
        0.58130081, 1.        ],
       [0.74      , 0.7037037 , 0.5       , 0.5       , 0.5       ,
        0.56097561, 1.        ],
       [0.22      , 0.33333333, 0.5       , 0.375     , 0.25      ,
        0.32113821, 1.        ],
       [0.8       , 1.        , 1.        , 0.875     , 1.        ,
        0.90243902, 1.        ],
       [0.76      , 0.62962963, 0.75      , 1.        , 0.75      ,
        0.73170732, 1.        ],
       [0.44      , 0.44444444, 0.25      , 0.375     , 0.5       ,
        0.31707317, 0.        ],
       [0.44      , 0.51851852, 0.75      , 0.875     , 0.75      ,
        0.53252033, 1.        ],
       [0.2       , 0.2962963 , 0.5       , 0.625     , 0.375     ,
        0.2195122 , 0.        ],
       [0.58      , 0.62962963, 0.5       , 0.5       , 0.375     ,
        0.58943089, 0.        ],
       [0.3       , 0.40740741, 0.25      , 0.375     , 0.125     ,
        0.18292683, 0.        ],
       [0.66      , 0.74074074, 0.75      , 0.75      , 0.875     ,
        0.76829268, 1.        ],
       [0.52      , 0.40740741, 0.5       , 0.5       , 0.625     ,
        0.26829268, 1.        ],
       [0.58      , 0.55555556, 0.5       , 0.5       , 0.625     ,
        0.48780488, 1.        ],
       [0.2       , 0.18518519, 0.        , 0.25      , 0.375     ,
        0.27642276, 0.        ],
       [0.84      , 0.92592593, 1.        , 1.        , 1.        ,
        0.93495935, 1.        ],
       [0.22      , 0.40740741, 0.5       , 0.625     , 0.75      ,
        0.31707317, 1.        ],
       [0.5       , 0.51851852, 0.25      , 0.75      , 0.5       ,
        0.47154472, 1.        ],
       [1.        , 0.74074074, 0.75      , 1.        , 1.        ,
        0.97560976, 1.        ],
       [0.22      , 0.14814815, 0.25      , 0.5       , 0.5       ,
        0.2195122 , 1.        ],
       [0.42      , 0.2962963 , 0.25      , 0.375     , 0.625     ,
        0.40650407, 1.        ],
       [0.74      , 0.74074074, 0.75      , 0.875     , 0.875     ,
        0.7195122 , 1.        ],
       [1.        , 0.77777778, 1.        , 0.75      , 0.75      ,
        0.91869919, 1.        ],
       [0.22      , 0.22222222, 0.25      , 0.5       , 0.25      ,
        0.35772358, 0.        ],
       [0.94      , 0.92592593, 0.75      , 0.875     , 0.875     ,
        0.93902439, 1.        ],
       [0.74      , 0.66666667, 0.75      , 0.75      , 0.875     ,
        0.67479675, 1.        ],
       [0.74      , 0.48148148, 0.75      , 0.75      , 0.875     ,
        0.57317073, 1.        ],
       [0.76      , 0.85185185, 1.        , 1.        , 1.        ,
        0.87804878, 1.        ],
       [0.62      , 0.66666667, 1.        , 1.        , 1.        ,
        0.85772358, 1.        ],
       [0.18      , 0.25925926, 0.25      , 0.5       , 0.625     ,
        0.2195122 , 0.        ],
       [0.26      , 0.44444444, 1.        , 1.        , 0.875     ,
        0.53252033, 0.        ],
       [0.22      , 0.11111111, 0.        , 0.5       , 0.75      ,
        0.08943089, 0.        ],
       [0.92      , 0.92592593, 1.        , 0.875     , 1.        ,
        0.8902439 , 1.        ],
       [0.6       , 0.37037037, 0.5       , 0.5       , 0.5       ,
        0.14634146, 0.        ],
       [0.98      , 0.85185185, 0.75      , 0.75      , 0.625     ,
        1.        , 1.        ],
       [0.56      , 0.62962963, 0.5       , 0.75      , 0.5       ,
        0.59349593, 0.        ],
       [0.16      , 0.44444444, 0.5       , 0.625     , 0.75      ,
        0.48780488, 0.        ],
       [0.12      , 0.07407407, 0.25      , 0.5       , 0.25      ,
        0.08130081, 1.        ],
       [0.22      , 0.22222222, 0.5       , 0.375     , 0.25      ,
        0.45121951, 1.        ],
       [0.36      , 0.37037037, 0.25      , 0.375     , 0.75      ,
        0.41463415, 1.        ],
       [0.3       , 0.33333333, 0.25      , 0.25      , 0.375     ,
        0.34146341, 0.        ],
       [0.28      , 0.37037037, 1.        , 1.        , 0.5       ,
        0.23577236, 0.        ],
       [0.08      , 0.        , 0.        , 0.125     , 0.25      ,
        0.00813008, 0.        ],
       [0.34      , 0.55555556, 0.25      , 0.75      , 0.625     ,
        0.14634146, 0.        ],
       [0.68      , 0.74074074, 0.75      , 0.875     , 0.875     ,
        0.77642276, 1.        ],
       [0.78      , 0.77777778, 1.        , 0.75      , 1.        ,
        0.79674797, 1.        ],
       [0.4       , 0.40740741, 0.5       , 0.25      , 0.625     ,
        0.41869919, 0.        ],
       [0.56      , 0.48148148, 0.5       , 0.25      , 0.5       ,
        0.53252033, 0.        ],
       [0.26      , 0.25925926, 0.25      , 0.5       , 0.625     ,
        0.29268293, 1.        ],
       [0.72      , 0.62962963, 0.5       , 0.625     , 0.625     ,
        0.57723577, 1.        ],
       [0.6       , 0.2962963 , 0.25      , 0.375     , 0.5       ,
        0.5203252 , 0.        ],
       [0.34      , 0.44444444, 0.25      , 0.375     , 0.5       ,
        0.12601626, 0.        ],
       [0.2       , 0.22222222, 0.        , 0.        , 0.375     ,
        0.27235772, 0.        ],
       [0.46      , 0.48148148, 0.25      , 0.375     , 0.25      ,
        0.44308943, 0.        ],
       [0.74      , 0.74074074, 0.75      , 0.875     , 1.        ,
        0.73170732, 0.        ],
       [0.76      , 0.81481481, 0.75      , 0.875     , 0.75      ,
        0.7398374 , 1.        ],
       [0.3       , 0.33333333, 0.25      , 0.125     , 0.375     ,
        0.12195122, 0.        ],
       [0.3       , 0.11111111, 0.75      , 0.5       , 0.875     ,
        0.37398374, 0.        ],
       [0.72      , 0.55555556, 0.5       , 0.5       , 0.625     ,
        0.6300813 , 0.        ],
       [0.6       , 0.62962963, 1.        , 1.        , 0.875     ,
        0.76422764, 1.        ],
       [0.38      , 0.44444444, 0.75      , 0.625     , 0.25      ,
        0.34146341, 0.        ],
       [0.64      , 0.62962963, 0.75      , 0.75      , 1.        ,
        0.72764228, 1.        ],
       [0.66      , 0.40740741, 0.5       , 0.75      , 0.75      ,
        0.44715447, 1.        ],
       [0.56      , 0.48148148, 0.25      , 0.75      , 0.75      ,
        0.23577236, 1.        ],
       [0.2       , 0.40740741, 0.5       , 0.625     , 0.5       ,
        0.33333333, 0.        ],
       [0.62      , 0.62962963, 0.75      , 0.625     , 0.75      ,
        0.41056911, 1.        ],
       [0.42      , 0.51851852, 0.75      , 0.875     , 0.875     ,
        0.67479675, 1.        ],
       [0.36      , 0.37037037, 0.25      , 0.5       , 0.625     ,
        0.46747967, 0.        ],
       [0.58      , 0.44444444, 0.5       , 0.5       , 0.625     ,
        0.54065041, 1.        ],
       [0.74      , 0.85185185, 0.75      , 0.75      , 0.875     ,
        0.8699187 , 1.        ],
       [0.96      , 0.81481481, 1.        , 0.875     , 1.        ,
        0.76829268, 1.        ],
       [0.5       , 0.40740741, 0.5       , 0.5       , 0.375     ,
        0.40243902, 0.        ],
       [0.6       , 0.7037037 , 0.25      , 0.625     , 0.625     ,
        0.58536585, 1.        ],
       [0.18      , 0.03703704, 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.5       , 0.48148148, 0.5       , 0.875     , 0.625     ,
        0.43902439, 0.        ],
       [0.78      , 0.77777778, 0.25      , 0.25      , 0.75      ,
        0.49593496, 1.        ],
       [0.56      , 0.62962963, 0.        , 0.375     , 0.625     ,
        0.48780488, 1.        ],
       [0.48      , 0.44444444, 0.5       , 0.625     , 0.375     ,
        0.3902439 , 0.        ]])

In [48]:
model = Sequential()
model.add(Dense(7, activation="relu", input_dim=7))
model.add(Dense(7, activation="relu"))
model.add(Dense(1, activation="linear"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [49]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 7)              │            56 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 7)              │            56 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 120 (480.00 B)

 Trainable params: 120 (480.00 B)

 Non-trainable params: 0 (0.00 B)

In [50]:
model.compile(loss="mean_squared_error", optimizer="Adam")

In [51]:
history = model.fit(X_train_scaled, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 357ms/step - loss: 0.6297 - val_loss: 0.6281
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.5884 - val_loss: 0.5800
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.5457 - val_loss: 0.5311
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.5038 - val_loss: 0.4821
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.4605 - val_loss: 0.4328
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.4133 - val_loss: 0.3831
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.3684 - val_loss: 0.3359
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.3241 - val_loss: 0.2913
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2818 - val_loss: 0.2496
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.2433 - val_loss: 0.2098
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.2060 - val_loss: 0.1736
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.1698 - val_loss: 0.1406
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1362 - val_loss: 0.1100
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.1056 - val_loss: 0.0812
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0780 - val_loss: 0.0565
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0556 - val_loss: 0.0375
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0388 - val_loss: 0.0244
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0275 - val_loss: 0.0168
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0210 - val_loss: 0.0131
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0184 - val_loss: 0.0121
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0185 - val_loss: 0.0126
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0191 - val_loss: 0.0135
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0199 - val_loss: 0.0140
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0202 - val_loss: 0.0140
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0200 - val_loss: 0.0135
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0194 - val_loss: 0.0128
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0185 - val_loss: 0.0121
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0179 - val_loss: 0.0115
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0171 - val_loss: 0.0111
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.0167 - val_loss: 0.0109
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0164 - val_loss: 0.0108
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0162 - val_loss: 0.0107
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0160 - val_loss: 0.0107
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0159 - val_loss: 0.0107
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.0158 - val_loss: 0.0106
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0156 - val_loss: 0.0105
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0155 - val_loss: 0.0104
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0153 - val_loss: 0.0102
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0151 - val_loss: 0.0101
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0149 - val_loss: 0.0099
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0148 - val_loss: 0.0098
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0147 - val_loss: 0.0097
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0145 - val_loss: 0.0096
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0144 - val_loss: 0.0095
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0142 - val_loss: 0.0094
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0141 - val_loss: 0.0094
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0139 - val_loss: 0.0093
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0138 - val_loss: 0.0092
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0136 - val_loss: 0.0091
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0135 - val_loss: 0.0090
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0134 - val_loss: 0.0089
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0132 - val_loss: 0.0088
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0131 - val_loss: 0.0088
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0130 - val_loss: 0.0087
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0129 - val_loss: 0.0086
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0127 - val_loss: 0.0085
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0126 - val_loss: 0.0084
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0125 - val_loss: 0.0083
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0124 - val_loss: 0.0083
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0122 - val_loss: 0.0082
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0121 - val_loss: 0.0081
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0120 - val_loss: 0.0080
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - val_loss: 0.0080
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0118 - val_loss: 0.0079
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0117 - val_loss: 0.0078
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0116 - val_loss: 0.0078
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0115 - val_loss: 0.0077
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0114 - val_loss: 0.0076
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0113 - val_loss: 0.0076
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0112 - val_loss: 0.0075
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0111 - val_loss: 0.0074
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0110 - val_loss: 0.0074
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0109 - val_loss: 0.0073
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0108 - val_loss: 0.0072
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0108 - val_loss: 0.0072
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0107 - val_loss: 0.0071
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0106 - val_loss: 0.0071
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0105 - val_loss: 0.0070
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0104 - val_loss: 0.0070
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0103 - val_loss: 0.0070
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0103 - val_loss: 0.0069
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0102 - val_loss: 0.0069
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0101 - val_loss: 0.0068
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0100 - val_loss: 0.0068
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0099 - val_loss: 0.0067
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0099 - val_loss: 0.0067
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0098 - val_loss: 0.0066
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0097 - val_loss: 0.0066
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0097 - val_loss: 0.0066
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0096 - val_loss: 0.0065
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0095 - val_loss: 0.0065
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0095 - val_loss: 0.0064
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0094 - val_loss: 0.0064
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0093 - val_loss: 0.0064
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0093 - val_loss: 0.0063
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0092 - val_loss: 0.0063
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0091 - val_loss: 0.0062
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0091 - val_loss: 0.0062
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0090 - val_loss: 0.0062
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0089 - val_loss: 0.0061

In [52]:
y_pred = model.predict(X_test_scaled)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

In [53]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.5542419149274929